import {StyleSheet} from 'react-native'
import Colors from './Colors'

export const buttonStyles= StyleSheet.create ({
    primary:{
        alignItems: 'center',
        width: 327,
        height: 58,
        borderRadius: 20,
        backgroundColor: Colors.Brand01,
        textAlign: "center",
        paddingVertical: 15,
        marginBottom: 25,
        justifyContent: 'center',
    },
    secondary:{
        alignItems: 'center', 
        width: 327,
        height: 58,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: Colors.Brand01,
        backgroundColor: Colors.FontWhite,
        textAlign: "center",
        paddingVertical: 15,
        justifyContent: 'center',
    },
    tertiary:{
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.Monochromatic10,
        borderColor: Colors.Monochromatic06,
        borderWidth: 1,
        borderRadius: 20,
        width: '85%',
        paddingVertical: 15,
        marginBottom: 10,
        paddingHorizontal: 20,
        justifyContent: 'center',
    },
    error: {
        width: 327,
        height: 58,
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        borderRadius: 20,
        backgroundColor: Colors.Error,
        textAlign: "center",
        shadowColor: Colors.Shadow,
        shadowOffset: {
          width: 0,
          height: 4,
        },
        shadowOpacity: 1,
        shadowRadius: 4,
        elevation: 4,
    },
    success: {
        width: 327,
        height: 58,
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        borderRadius: 20,
        backgroundColor: Colors.Success,
        textAlign: "center",
        shadowColor: Colors.Shadow,
        shadowOffset: {
          width: 0,
          height: 4,
        },
        shadowOpacity: 1,
        shadowRadius: 4,
        elevation: 4,
    },
    disable: {
        width: 327,
        height: 58,
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        borderRadius: 20,
        backgroundColor: Colors.Monochromatic08,
        textAlign: "center",
        shadowColor: Colors.Shadow,
        shadowOffset: {
          width: 0,
          height: 4,
        },
        shadowOpacity: 1,
        shadowRadius: 4,
        elevation: 4,
    },

})